CREATE PROCEDURE "bpvs_FE_FacturaCabecera"
AS
BEGIN

	
	Declare cantidad int default 0;

	T_REPETIDOS = 
	SELECT T0."DOC_Serie"||'-'||T0."DOC_Codigo"||'-'||T0."DOC_Numero" AS "Documento",
		   COUNT(T0."FE_DocEntry") AS "Contador"
	FROM "_SYS_BIC"."VS_FE_207/C_BASE" T0 
	WHERE T0."FE_FormSAP" != 'ENTREGA' OR (T0."FE_FormSAP" = 'ENTREGA' AND LEFT(T0."DOC_Serie",1) = 'T')
	GROUP BY T0."DOC_Serie",T0."DOC_Codigo",T0."DOC_Numero";
	
	SELECT Count("Documento") into cantidad
	FROM :T_REPETIDOS
	WHERE "Contador">1;
	
	IF cantidad > 0 THEN	
		SELECT repetidos ||', '||"Documento"||'('||TO_VARCHAR("Contador")||')' INTO repetidos
		FROM :T_REPETIDOS
		WHERE "Contador">1;
		
		SELECT
			NULL AS "DocIdentidad_Nro",
		 	NULL AS "DocIdentidad_Tipo",
			NULL AS "RazonSocial",
		 	NULL AS "NombreComercial",
		 	NULL AS "PersonContacto",
		 	NULL AS "EMail",
		 	NULL AS "Telefono",
		 	NULL AS "Telefono_1",
		 	NULL AS "Web",
		 	NULL AS "DIR_Pais",
		 	NULL AS "DIR_Departamento",
		 	NULL AS "DIR_Provincia",
		 	NULL AS "DIR_Distrito",
		 	NULL AS "DIR_Direccion",
		 	NULL AS "DIR_NomCalle",
		 	NULL AS "DIR_NroCasa",
		 	NULL AS "DIR_Ubigeo",
		 	NULL AS "DIR_Urbanizacion",
		 	NULL AS "SN_DocIdentidad_Nro",
		 	NULL AS "SN_DocIdentidad_Tipo",
		 	NULL AS "SN_RazonSocial",
		 	NULL AS "SN_NombreComercial",
		 	NULL AS "SN_EMail",
			NULL AS "SN_EMail_Secundario",
		 	NULL AS "SN_SegundoNombre",
		 	NULL AS "SN_DIR_Pais",
		 	NULL AS "SN_DIR_Departamento",
		 	NULL AS "SN_DIR_Provincia",
		 	NULL AS "SN_DIR_Distrito",
		 	NULL AS "SN_DIR_Direccion",
		 	NULL AS "SN_DIR_NomCalle",
		 	NULL AS "SN_DIR_NroCasa",
		 	NULL AS "SN_DIR_Ubigeo",
		 	NULL AS "SN_DIR_Urbanizacion",
		 	NULL AS "DOC_Serie",
		 	NULL AS "DOC_Numero",
		 	NULL AS "DOC_Id",
		 	NULL AS "DOC_FechaEmision",
		 	NULL AS "DOC_FechaVencimiento",
		 	NULL AS "DOC_Dscrpcion",
		 	NULL AS "DOC_Codigo",
		 	NULL AS "DOC_MON_Nombre",
		 	NULL AS "DOC_MON_Codigo",
		 	NULL AS "DOC_Descuento",			
		 	NULL AS "DOC_MontoTotal",
		 	NULL AS "DOC_Importe",			
		 	NULL AS "DOC_CondPago",
		 	NULL AS "DOC_PorcImpuesto",
		 	NULL AS "ANTICIPO_Id",
		 	NULL AS "ANTICIPO_Tipo",
		 	NULL AS "ANTICIPO_Monto",
		 	NULL AS "ANTICIPO_Nro_Doc_ID",
		 	NULL AS "ANTCIPO_Tipo_Doc_ID",
		 	NULL AS "SUNAT_Transact",
		 	NULL AS "FE_DocEntry",
		 	NULL AS "FE_ObjectType",
		 	NULL AS "FE_Estado",
		 	NULL AS "FE_TipoTrans",
		 	NULL AS "FE_Id",
		 	NULL AS "FE_DocNum",
		 	NULL AS "FE_FormSAP",
		 	NULL AS "REFDOC_Tipo",
		 	NULL AS "REFDOC_Id",
		 	NULL AS "REFDOC_MotivCode",
		 	NULL AS "REFDOC_MotivDesc",
		 	NULL AS "FE_Comentario",
		 	'ERR:0004' AS "FE_ErrCod",
		 	repetidos AS "FE_ErrMsj",
		 	0 AS "FE_Errores",
		 	0 AS "FE_MaxSalto",
		 	0 AS "FE_Saltos",
		 	NULL AS "RET_Regimen",
		 	NULL AS "RET_Tasa",
		 	NULL AS "Observaciones",
		 	0 AS "ImportePagado",
		 	NULL AS "MonedaPagado",
		 	NULL AS "FechaDOCRef",
		 	NULL AS "FechaVenDOCRef",
		 	0 AS "ImporteDOCRef",
			NULL AS "DOC_OtrosCargos",
			NULL AS "TipoOperacionSunat",				
			NULL AS "DOC_PorDescuento",
			NULL AS "DOC_ImporteTotal",
			NULL AS "DOC_ImpuestoTotal",
			NULL AS "DOC_DescuentoTotal",
			NULL AS "CuentaDetraccion",
			NULL AS "CodigoDetraccion",
			NULL AS "PorcDetraccion",
			NULL AS "MontoDetraccion",
			NULL AS "CodigoPago",
			NULL AS "DOC_SinPercepcion",
			NULL AS "DOC_MonPercepcion",
			NULL AS "DOC_PorPercepcion",
			NULL AS "MontoRetencion"
		FROM DUMMY;
	ELSE -- No existen Repetidos
		SELECT TOP 10
			 "DocIdentidad_Nro",
			 "DocIdentidad_Tipo",
			 "RazonSocial",
			 "NombreComercial",
			 "PersonContacto",
			 "EMail",
			 "Telefono",
			 "Telefono_1",
			 "Web",
			 "DIR_Pais",
			 "DIR_Departamento",
			 "DIR_Provincia",
			 "DIR_Distrito",
			 "DIR_Direccion",
			 "DIR_NomCalle",
			 "DIR_NroCasa",
			 "DIR_Ubigeo",
			 "DIR_Urbanizacion",
			 --CASE WHEN ("FE_ObjectType" = '15') 
			 		--THEN (CASE WHEN (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry" ) != '' THEN (SELECT "LicTradNum" FROM OCRD WHERE "CardCode" = (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry")) ELSE "SN_DocIdentidad_Nro" END )
			 	 -- ELSE "SN_DocIdentidad_Nro" END  AS "SN_DocIdentidad_Nro",
			 "SN_DocIdentidad_Nro",
			-- CASE WHEN ("FE_ObjectType" = '15') 
			 	--	THEN (CASE WHEN (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry" ) != '' THEN (SELECT "U_BPP_BPTD" FROM OCRD WHERE "CardCode" = (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry")) ELSE "SN_DocIdentidad_Tipo" END )
			-- ELSE "SN_DocIdentidad_Tipo" END  AS "SN_DocIdentidad_Tipo",			
			 "SN_DocIdentidad_Tipo",
			 --CASE WHEN ("FE_ObjectType" = '15') 
			 	--	THEN (CASE WHEN (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry" ) != '' THEN (SELECT "CardName" FROM OCRD WHERE "CardCode" = (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry")) ELSE "SN_RazonSocial" END )
			 --ELSE "SN_RazonSocial" END  AS "SN_RazonSocial",			 
			 "SN_RazonSocial",
			-- CASE WHEN ("FE_ObjectType" = '15') 
			 	--	THEN (CASE WHEN (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry" ) != '' THEN (SELECT "U_VS_NOMCOM" FROM OCRD WHERE "CardCode" = (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry")) ELSE "SN_NombreComercial" END )
			-- ELSE "SN_NombreComercial" END  AS "SN_NombreComercial",
			 "SN_NombreComercial",
			-- CASE WHEN ("FE_ObjectType" = '15') 
			 	--	THEN (CASE WHEN (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry" ) != '' THEN (SELECT "E_Mail" FROM OCRD WHERE "CardCode" = (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry")) ELSE "SN_EMail" END )
			 --ELSE "SN_EMail" END  AS "SN_EMail",
			 "SN_EMail",
			 --CASE WHEN ("FE_ObjectType" = '15') 
			 	--	THEN (CASE WHEN (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry" ) != '' THEN (SELECT "U_VS_MAIL_SEC" FROM OCRD WHERE "CardCode" = (SELECT IFNULL(G.U_BPP_MDSN,'') FROM ODLN G WHERE G."DocEntry" = "FE_DocEntry")) ELSE "SN_EMail_Secundario" END )
			-- ELSE "SN_EMail_Secundario" END  AS "SN_EMail_Secundario",
			-- "SN_EMail_Secundario",
			 "SN_SegundoNombre",
			 "SN_DIR_Pais",
			 "SN_DIR_Departamento",
			 "SN_DIR_Provincia",
			 "SN_DIR_Distrito",
			 "SN_DIR_Direccion",
			 "SN_DIR_NomCalle",
			 "SN_DIR_NroCasa",
			 "SN_DIR_Ubigeo",
			 "SN_DIR_Urbanizacion",
			 "DOC_Serie",
			 "DOC_Numero",
			 "DOC_Id",
			 "DOC_FechaEmision",
			 "DOC_FechaVencimiento",
			 "DOC_Dscrpcion",
			 "DOC_Codigo",
			 "DOC_MON_Nombre",
			 "DOC_MON_Codigo",
			 "DOC_Descuento",
			 "DOC_MontoTotal" - IFNULL("DOC_MonPercepcion",0.00) AS  "DOC_MontoTotal",
			 "DOC_Importe",
			 "DOC_CondPago",
			 "DOC_PorcImpuesto",
			 "ANTICIPO_Id",
			 "ANTICIPO_Tipo",
			 "ANTICIPO_Monto",
			 "ANTICIPO_Nro_Doc_ID",
			 "ANTCIPO_Tipo_Doc_ID",
			 "SUNAT_Transact",
			 "FE_DocEntry",
			 "FE_ObjectType",
			 "FE_Estado",
			 "FE_TipoTrans",
			 "FE_Id",
			 "FE_DocNum",
			 "FE_FormSAP",
			 "REFDOC_Tipo",
			 "REFDOC_Id",
			 "REFDOC_MotivCode",
			 "REFDOC_MotivDesc",
			 "FE_Comentario",
			 "FE_ErrCod",
			 "FE_ErrMsj",
			 "FE_Errores",
			 "FE_MaxSalto",
			 "FE_Saltos",
			 "RET_Regimen",
			 "RET_Tasa",
			 "Observaciones",
			 "ImportePagado",
			 "MonedaPagado",
			 "FechaDOCRef",
			 "FechaVenDOCRef",
			 "ImporteDOCRef",
			 "DOC_OtrosCargos",
			 "TipoOperacionSunat",				
			 "DOC_PorDescuento",
			 "DOC_ImporteTotal",
			 "DOC_ImpuestoTotal" - IFNULL("DOC_MonPercepcion",0.00) AS "DOC_ImpuestoTotal",
			 "DOC_DescuentoTotal",
			 "CuentaDetraccion",
			 "CodigoDetraccion",
			 "PorcDetraccion",
			 "MontoDetraccion",
			 "CodigoPago",
			  "DOC_SinPercepcion"- IFNULL("DOC_MonPercepcion",0.00) AS  "DOC_SinPercepcion",
			  "DOC_MonPercepcion",
              "DOC_PorPercepcion",
			  (SELECT left(CAST(IFNULL(B.U_VS_CDRRSM,'') AS nvarchar),20) AS A FROM OINV B WHERE B."DocEntry" = "FE_DocEntry" AND left(CAST(IFNULL(B.U_VS_CDRRSM,'') AS nvarchar),1) IN ('0','1','2','3','4','5','6','7','8','9')) AS "Ticket_Baja",
			  "MontoRetencion"
		FROM "_SYS_BIC"."VS_FE_207/C_BASE"
		WHERE /*(LEFT("FE_Id",2) != '03' OR (LEFT("FE_Id",2) = '03' AND RIGHT("FE_Id",1) != 'B')) AND*/ "FE_FormSAP" != 'ENTREGA' OR ("FE_FormSAP" = 'ENTREGA' AND (LEFT("DOC_Serie",1) = 'T' OR LEFT("DOC_Serie",1) = 'V'));
	END IF;	
END;