name: Connect to Windows Server via GitHub Actions

on:
  push:
    branches:
      - main  # Puedes ajustar el trigger según tu necesidad

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Connect to Windows Server
      shell: pwsh
      run: |
        try {
          $session = New-PSSession -ComputerName 119.8.146.122 -Port 63034 -Credential (New-Object System.Management.Automation.PSCredential('Operador_vs04', (ConvertTo-SecureString 'aNkf2BSN#TCcKYnp' -AsPlainText -Force))) -UseSSL -Authentication Negotiate

          if ($session -ne $null) {
            Write-Output "✅ Conexión exitosa al servidor Windows."
            Remove-PSSession $session
          } else {
            Write-Error "❌ No se pudo establecer la conexión."
          }
        }
        catch {
          Write-Error "❌ Error durante la conexión: $($_.Exception.Message)"
        }
