name: SAP HANA Connection Workflow

on:
  push:
    branches:
      - main  # Puedes configurar otro trigger o rama

jobs:
  connect_and_query_hana:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 1: Conectar al servidor Windows usando WinRM
    - name: Connect to Windows Server via WinRM
      uses: Maxym/psrp-client@v1
      with:
        hostname: ${{ secrets.WINDOWS_SERVER_IP }}
        username: ${{ secrets.WINDOWS_SERVER_USER }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        command: |
          echo "Conexión establecida al servidor Windows"
          # Listar archivos en el disco C para verificar la conexión
          dir C:\

    # Paso 2: Conectar a SAP HANA desde el servidor Windows
    - name: Connect to SAP HANA Database
      uses: Maxym/psrp-client@v1
      with:
        hostname: ${{ secrets.WINDOWS_SERVER_IP }}
        username: ${{ secrets.WINDOWS_SERVER_USER }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        command: |
          echo "Conectando a SAP HANA..."
          # Ejecutar el comando para conectarse a SAP HANA
          hdbsql -n ${{ secrets.HANA_HOST }}:${{ secrets.HANA_PORT }} -u ${{ secrets.HANA_USER }} -p ${{ secrets.HANA_PASSWORD }} "SET SCHEMA ${{ secrets.SCHEMA }}; SELECT 1 FROM DUMMY;"

    # Mensaje final de éxito
    - name: Finalize
      run: echo "Conexión a SAP HANA y servidor Windows exitosa"
