name: Connect to Windows Server

on:
  push:
    branches:
      - main

jobs:
  remote-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PowerShell
        run: |
          sudo apt update
          sudo apt install -y powershell

      - name: Connect to Windows Server via WinRM
        run: |
          pwsh -Command "
            # Convertir la contraseña en un objeto seguro
            $securePassword = ConvertTo-SecureString '${{ secrets.WIN_PASSWORD }}' -AsPlainText -Force
            $credential = New-Object System.Management.Automation.PSCredential ('${{ secrets.WIN_USERNAME }}', $securePassword)

            # Crear la sesión remota usando WinRM
            $sessionOptions = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
            $session = New-PSSession -ComputerName '${{ secrets.WIN_HOST }}' -Port ${{ secrets.WIN_PORT }} -Credential $credential -UseSSL -SessionOption $sessionOptions -Authentication Negotiate

            # Verificar si la sesión fue creada exitosamente
            if ($session -ne $null) {
              Write-Output '✅ Conexión exitosa al servidor Windows.'
              
              # Ejecutar un comando en el servidor remoto (puedes personalizarlo)
              Invoke-Command -Session $session -ScriptBlock { Get-ComputerInfo | Select-Object OSName, OSVersion }

              # Cerrar la sesión después de ejecutar los comandos
              Remove-PSSession $session
            } else {
              Write-Error '❌ No se pudo establecer la conexión.'
            }
          "
