name: Connect to SAP HANA via SSH and Run Queries

on:
  push:
    branches:
      - main

jobs:
  connect-hana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into SAP HANA Server and Execute Queries
        env:
          SSH_HOST: "176.52.135.159"
          SSH_PORT: "22234"
          SSH_USER: "jbecerra"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HANA_USER: "SYSTEM"
          HANA_PASSWORD: "H4N4B1Admin"
          QUERY: "SELECT CURRENT_TIMESTAMP FROM DUMMY;"
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST <<EOF
            echo "Connected to SAP HANA Server"
            cd /hana/shared/NDB/HDB00/exe
            echo "Running hdbsql..."
            ./hdbsql -u "$HANA_USER" -p "$HANA_PASSWORD" -m <<EOSQL
            $QUERY
            EOSQL
          EOF
