name: Connect to Windows Server via GitHub Actions

on:
  push:
    branches:
      - main  # Puedes ajustar el trigger según tu necesidad

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Connect to Windows Server
      shell: pwsh
      run: |
        try {
          $session = New-PSSession -HostName 119.8.146.122 -Port 63034 -UserName 'Operador_vs04' -KeyFilePath '/path/to/private/key'
        
          if ($session -ne $null) {
            Write-Output "✅ Conexión exitosa al servidor Windows."
            Remove-PSSession $session
          } else {
            Write-Error "❌ No se pudo establecer la conexión."
          }
        }
        catch {
          Write-Error "❌ Error durante la conexión: $($_.Exception.Message)"
        }
