name: Connect to Windows Server

on:
  push:
    branches:
      - main

jobs:
  remote-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PowerShell
        run: |
          sudo apt update
          sudo apt install -y powershell

      - name: Connect to Windows Server via WinRM
        run: |
                  $username = "${{ secrets.WINDOWS_USERNAME }}"
                  $password = ConvertTo-SecureString "${{ secrets.WINDOWS_PASSWORD }}" -AsPlainText -Force
                  $cred = New-Object System.Management.Automation.PSCredential ($username, $password)
                  
                  $session = New-PSSession -ComputerName 119.8.146.122 -Port 63034 -Credential $cred -UseSSL -Authentication Negotiate
        
                  if ($session -ne $null) {
                    Write-Output "✅ Conexión exitosa al servidor Windows."
                    Remove-PSSession $session
                  } else {
                    Write-Error "❌ No se pudo establecer la conexión."
                  }
