name: Connect to Windows Server via GitHub Actions

on:
  push:
    branches:
      - main  # Puedes ajustar el trigger según tu necesidad

jobs:
  connect_to_windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PowerShell and WinRM client
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell
        pwsh -Command "Install-Module -Name PSRPClient -Force -Scope CurrentUser"

    - name: Connect to Windows Server using WinRM
      run: |
        pwsh -Command "
          try {
            # Establecer la conexión
            $session = New-PSSession -ComputerName '${{ secrets.WINDOWS_SERVER_IP }}' `
                                     -Port ${{ secrets.WINDOWS_SERVER_PORT }} `
                                     -Credential (New-Object System.Management.Automation.PSCredential('${{ secrets.WINDOWS_SERVER_USER }}', (ConvertTo-SecureString '${{ secrets.WINDOWS_SERVER_PASSWORD }}' -AsPlainText -Force))) `
                                     -Authentication Negotiate `
                                     -UseSSL:$false

            # Verificar la conexión
            if ($session.State -eq 'Opened') {
              Write-Output '✅ Conexión exitosa al servidor Windows.'
              Invoke-Command -Session $session -ScriptBlock { hostname; Get-Date }
            } else {
              Write-Error '❌ No se pudo establecer la conexión al servidor.'
            }

            #  Cerrar sesión
            Remove-PSSession $session
          }
          catch {
            Write-Error '❌ Error durante la conexión:'
            Write-Error $_.Exception.Message
          }
        "
