name: Conexión SSH Remota con Usuario y Contraseña

on:
  push:
    branches:
      - main

jobs:
  remote-ssh-connection:
    runs-on: windows-latest

    steps:
      - name: Instalar sshpass
        run: |
          sudo apt-get install -y sshpass

      - name: Conectar vía SSH y ejecutar comandos
        shell: bash
        run: |
          # Conexión a través de SSH con usuario y contraseña
          sshpass -p "${{ secrets.WINDOWS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.WINDOWS_USERNAME }}@101.44.1.161 "echo 'Comando ejecutado remotamente'"
