name: Conexión SSH Remota

on:
  push:
    branches:
      - main

jobs:
  remote-ssh-connection:
    runs-on: windows-latest

    steps:
      - name: Conectar vía SSH y ejecutar comandos
        shell: bash
        run: |
          # Conectar a través de SSH
          ssh ${{ secrets.WINDOWS_USERNAME }}@101.44.1.161 "echo 'Comando ejecutado remotamentse'"
