name: Conexión SSH Remota con Usuario y Contraseña (Windows)

on:
  push:
    branches:
      - main

jobs:
  remote-ssh-connection:
    runs-on: windows-latest

    steps:
      - name: Descargar y configurar plink
        run: |
          Invoke-WebRequest -Uri "https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe" -OutFile "$env:USERPROFILE\plink.exe"

      - name: Conectar vía SSH y ejecutar comandos
        run: |
          $username = "${{ secrets.WINDOWS_USERNAME }}"
          $password = "${{ secrets.WINDOWS_PASSWORD }}"
          $host = "101.44.1.161"
          $command = "echo 'Comando ejecutado remotamente'"

          # Usar plink para la conexión SSH y ejecutar el comando
          & "$env:USERPROFILE\plink.exe" -ssh $username@$host -pw $password -batch $command
