name: Connect to SAP HANA Databases using Python

on:
  push:
    branches:
      - main

jobs:
  connect-hana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install SAP HANA Python Driver
        run: |
          pip install hdbcli

      - name: Connect to SAP HANA and Run Queries
        env:
          HANA_HOST: ${{ secrets.HANA_HOST }}
          HANA_PORT: ${{ secrets.HANA_PORT }}
          HANA_USER: ${{ secrets.HANA_USER }}
          HANA_PASSWORD: ${{ secrets.HANA_PASSWORD }}
          DATABASES: "20100151546 20100172624 20106836451"
        run: |
          python - <<EOF
          from hdbcli import dbapi
          import os

          HANA_HOST = os.getenv("HANA_HOST")
          HANA_PORT = os.getenv("HANA_PORT")
          HANA_USER = os.getenv("HANA_USER")
          HANA_PASSWORD = os.getenv("HANA_PASSWORD")
          DATABASES = os.getenv("DATABASES").split()

          for db in DATABASES:
              print(f"Connecting to database: {db}")
              conn = dbapi.connect(
                  address=HANA_HOST,
                  port=int(HANA_PORT),
                  user=HANA_USER,
                  password=HANA_PASSWORD,
                  database=db
              )
              cursor = conn.cursor()
              cursor.execute("SELECT CURRENT_TIMESTAMP FROM DUMMY;")
              result = cursor.fetchall()
              print(f"Timestamp from {db}: {result}")
              cursor.close()
              conn.close()
          EOF
