name: SAP HANA Connection Workflow

on:
  push:
    branches:
      - main  # Puedes configurar otro trigger o rama

jobs:
  connect_and_query_hana:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 1: Conectar al servidor Windows usando WinRM
    - name: Connect to Windows Server via WinRM
      uses: mcmilk/psrp-client@v1
      with:
        hostname: ${{ secrets.WINDOWS_SERVER_IP }}
        username: ${{ secrets.WINDOWS_SERVER_USER }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        command: |
          echo "Intentando conectar al servidor Windows..."
          if ($?) {
            Write-Host "✅ Conexión exitosa al servidor Windows"
          } else {
            Write-Error "❌ Error al conectar al servidor Windows"
            exit 1
          }
          # Aquí puedes agregar cualquier comando adicional que necesites
          dir C:\

    # Paso 2: Conectar a SAP HANA desde el servidor
    - name: Connect to SAP HANA Database
      uses: mcmilk/psrp-client@v1
      with:
        hostname: ${{ secrets.WINDOWS_SERVER_IP }}
        username: ${{ secrets.WINDOWS_SERVER_USER }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        command: |
          echo "Intentando conectar a SAP HANA..."
          hdbsql -n ${{ secrets.HANA_HOST }}:${{ secrets.HANA_PORT }} -u ${{ secrets.HANA_USER }} -p ${{ secrets.HANA_PASSWORD }} "SET SCHEMA ${{ secrets.SCHEMA }}; SELECT 1 FROM DUMMY;"
          
          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Conexión exitosa a SAP HANA y consulta ejecutada correctamente"
          } else {
            Write-Error "❌ Error al conectar a SAP HANA o ejecutar la consulta"
            exit 1
          }
