name: SAP HANA Connection Workflow

on:
  push:
    branches:
      - main  # Puedes configurar otro trigger o rama

jobs:
  hana_connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup environment variables for SAP HANA connection
      run: |
        echo "HANA_HOST=${{ secrets.HANA_HOST }}" >> $GITHUB_ENV
        echo "HANA_PORT=${{ secrets.HANA_PORT }}" >> $GITHUB_ENV
        echo "HANA_USER=${{ secrets.HANA_USER }}" >> $GITHUB_ENV
        echo "HANA_PASSWORD=${{ secrets.HANA_PASSWORD }}" >> $GITHUB_ENV
        echo "SCHEMA=${{ secrets.SCHEMA }}" >> $GITHUB_ENV

    - name: Test SAP HANA connection
      run: |
        echo "Testing SAP HANA connection"
        hdbsql -n $HANA_HOST:$HANA_PORT -u $HANA_USER -p $HANA_PASSWORD "SET SCHEMA $SCHEMA; SELECT 1 FROM DUMMY"
