name: Connect to SAP HANA via SSH and Verify Connection

on:
  push:
    branches:
      - main

jobs:
  connect-hana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into SAP HANA Server and Verify Connection
        env:
          SSH_HOST: "176.52.135.159"
          SSH_PORT: "22234"
          SSH_USER: "jbecerra"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          
          sshpass -p "$SSH_PASSWORD" ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST <<EOF
            echo "✅ Connection to SAP HANA Server successful!"
            echo "Switching to root user..."
            sudo su -c "
              cd /hana/shared/NDB/HDB00/exe || exit 1
              echo '✅ Access to /hana/shared/NDB/HDB00/exe successful!'
            "
          EOF
