name: Ejecutar Comandos Remotos con PsExec

on:
  push:
    branches:
      - main

jobs:
  execute-remote-command:
    runs-on: windows-latest  # Entorno Windows

    steps:
      - name: Descargar PsExec
        run: |
          Invoke-WebRequest -Uri "https://download.sysinternals.com/files/PSTools.zip" -OutFile "C:\temp\PSTools.zip"
          Expand-Archive "C:\temp\PSTools.zip" -DestinationPath "C:\temp\PsTools"

      - name: Ejecutar comando remoto
        run: |
          $username = "${{ secrets.WINDOWS_USERNAME }}"
          $password = ConvertTo-SecureString "${{ secrets.WINDOWS_PASSWORD }}" -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($username, $password)

          # Usar PsExec para ejecutar un comando remoto
          & "C:\temp\PsTools\PsExec.exe" \\119.8.146.122 -u $username -p $password cmd /c "echo Hello, World!"
