name: Connect to Multiple SAP HANA Databases

on:
  push:
    branches:
      - main

jobs:
  connect-hana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HANA Client
        run: |
          wget https://tools.hana.ondemand.com/additional/HDB_CLIENT_LINUX_X86_64.tar.gz
          tar -xvzf HDB_CLIENT_LINUX_X86_64.tar.gz
          sudo ./HDB_CLIENT_LINUX_X86_64/setup.sh --batch

      - name: Connect and Run Queries on Each Database
        env:
          HANA_HOST: ${{ secrets.HANA_HOST }}
          HANA_PORT: ${{ secrets.HANA_PORT }}
          HANA_USER: ${{ secrets.HANA_USER }}
          HANA_PASSWORD: ${{ secrets.HANA_PASSWORD }}
          DATABASES: "20100151546 20100172624 20106836451"  # Lista de bases de datos
        run: |
          echo "Connecting to SAP HANA and executing queries..."
          
          for DB in $DATABASES; do
            echo "Connecting to database: $DB"
            ./HDB_CLIENT_LINUX_X86_64/hdbsql -n $HANA_HOST:$HANA_PORT -u $HANA_USER -p $HANA_PASSWORD -d $DB -m <<EOF
            SELECT CURRENT_TIMESTAMP FROM DUMMY;
            EOF
          done
