name: Test SAP HANA Connection and Run SELECT

on:
  push:
    branches:
      - main

jobs:
  test-hana-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into SAP HANA Server and Run SELECT Query
        env:
          SSH_HOST: "176.52.135.159"
          SSH_PORT: "22234"
          SSH_USER: "jbecerra"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HANA_USER: "SYSTEM"
          HANA_PASSWORD: "H4N4B1Admin"
          SCHEMA: "SBO_20510511906_MAFIE_TEST"
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

          sshpass -p "$SSH_PASSWORD" ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST <<EOF
            echo "Connection to SAP HANA Server successful"
            
            # Cambiamos a root
            sudo su - root <<EOC
              cd /hana/shared/NDB/HDB00/exe || exit 1
              echo "Access to /hana/shared/NDB/HDB00/exe successful"

              echo "Running SELECT query..."
              RESULT=\$(./hdbsql -u "$HANA_USER" -p "$HANA_PASSWORD" -d "$SCHEMA" -m -C "SELECT CURRENT_TIMESTAMP FROM DUMMY;")

              echo "Query result:"
              echo "\$RESULT"
            EOC
          EOF

          echo "GitHub Action completed successfully"
          exit 0
