name: Execute SAP HANA Stored Procedure

on:
  push:
    branches:
      - main

jobs:
  execute-hana-procedure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to SAP HANA and Execute Stored Procedure
        env:
          SSH_HOST: "176.52.135.159"
          SSH_PORT: "22234"
          SSH_USER: "jbecerra"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HANA_USER: "SYSTEM"
          HANA_PASSWORD: ${{ secrets.HANA_PASSWORD }}
          SCHEMA: "SBO_20510511906_MAFIE_TEST"
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

          sshpass -p "$SSH_PASSWORD" ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOSSH'
          echo "Conectado al servidor SAP HANA"

          # Elevar privilegios a root y ejecutar el comando
          echo "$SSH_PASSWORD" | sudo -S su - root << 'EOROOT'
          cd /hana/shared/NDB/HDB00/exe

          # Ejecutar el CALL al procedimiento almacenado
          ./hdbsql -u "$HANA_USER" -p "$HANA_PASSWORD" -d NDB << 'EOSQL'
          CALL "$SCHEMA"."bpvs_FE_FacturaCabecera"();
          EOSQL

          echo "Procedimiento ejecutado exitosamente"
          EOROOT
          EOSSH

          echo "GitHub Action completado"
