name: Execute SAP HANA Stored Procedure

on:
  push:
    branches:
      - main

jobs:
  execute-hana-procedure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to SAP HANA and Execute SP
        env:
          SSH_HOST: "176.52.135.159"
          SSH_PORT: "22234"
          SSH_USER: "jbecerra"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HANA_USER: "SYSTEM"
          HANA_PASSWORD: ${{ secrets.HANA_PASSWORD }}
          SCHEMA: "SBO_20510511906_MAFIE_TEST"
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

          echo "Iniciando conexión SSH..."
          sshpass -p "$SSH_PASSWORD" ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOSSH'
          echo "Conectado al servidor SAP HANA"

          # Cambiar a root (sin redirecciones innecesarias)
          echo "$SSH_PASSWORD" | sudo -S su - root

          # Verificar acceso al directorio
          if cd /hana/shared/NDB/HDB00/exe; then
            echo "Acceso al directorio de HANA exitoso"

            # Ejecutar procedimiento almacenado
            echo "Ejecutando procedimiento almacenado..."
            ./hdbsql -u "SYSTEM" -p "$HANA_PASSWORD" -d NDB -ajx "CALL SBO_20510511906_MAFIE_TEST.\"bpvs_FE_FacturaCabecera\"()"

            echo "Ejecución completada correctamente"
          else
            echo "Error: No se pudo acceder al directorio de HANA"
            exit 1
          fi

          echo "Cerrando sesión SSH..."
          exit 0
          EOSSH

          echo "GitHub Action completada correctamente"
