name: Drop SAP HANA Stored Procedure

on:
  push:
    branches:
      - main

jobs:
  drop-hana-procedure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into SAP HANA Server and Drop Procedure
        env:
          SSH_HOST: "176.52.135.159"
          SSH_PORT: "22234"
          SSH_USER: "jbecerra"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HANA_USER: "SYSTEM"
          HANA_PASSWORD: "H4N4B1Admin"
          SCHEMA: "SBO_20510511906_MAFIE_TEST"
          PROCEDURE: "bpvs_FE_FacturaCabecera"
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          
          sshpass -p "$SSH_PASSWORD" ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST <<'EOF'
            echo "Connection to SAP HANA Server successful"
            echo "Switching to root user"
            sudo su -c "
              cd /hana/shared/NDB/HDB00/exe || exit 1
              echo 'Access to /hana/shared/NDB/HDB00/exe successful'

              echo 'Deleting procedure if it exists'
              DROP_RESULT=\$(./hdbsql -u \"$HANA_USER\" -p \"$HANA_PASSWORD\" -d \"$SCHEMA\" -m -C \"DROP PROCEDURE IF EXISTS \\\"$SCHEMA\\\".\\\"$PROCEDURE\\\";\" 2>&1)
              
              if echo \"\$DROP_RESULT\" | grep -q 'could not be dropped'; then
                echo 'ERROR: Procedure could not be dropped, check for dependencies'
                exit 1
              fi

              echo 'Procedure deleted successfully'

              echo 'Verifying if procedure was removed'
              CHECK_EXISTENCE=\$(./hdbsql -u \"$HANA_USER\" -p \"$HANA_PASSWORD\" -d \"$SCHEMA\" -m -C \"SELECT * FROM SYS.PROCEDURES WHERE SCHEMA_NAME = '$SCHEMA' AND PROCEDURE_NAME = '$PROCEDURE';\")

              if [ -z \"\$CHECK_EXISTENCE\" ]; then
                echo 'Procedure does not exist anymore'
              else
                echo 'WARNING: Procedure might still exist, check manually'
              fi
            "
          EOF

          echo "GitHub Action completed successfully"
          exit 0
