name: Execute SAP HANA Stored Procedure

on:
  push:
    branches:
      - main

jobs:
  execute-hana-procedure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to SAP HANA and Execute SP
        env:
          SSH_HOST: "176.52.135.159"
          SSH_PORT: "22234"
          SSH_USER: "jbecerra"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HANA_USER: "SYSTEM"
          HANA_PASSWORD: ${{ secrets.HANA_PASSWORD }}
          SCHEMA: "SBO_20510511906_MAFIE_TEST"
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

          sshpass -p "$SSH_PASSWORD" ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << "EOSSH"
          echo "Ejecutando como root..."
          
          # Comando replicado del manual exitoso, con escapes y variables
          sudo su - root -c "cd /hana/shared/NDB/HDB00/exe && ./hdbsql -u '$HANA_USER' -p '$HANA_PASSWORD' -d NDB -ajx \"CALL \\\\\\\"$SCHEMA\\\\\\\".\\\\\\\"bpvs_FE_FacturaCabecera\\\\\\\"()\""
          
          EOSSH
